export const teamList = [
    {id:2, src:"krystian", name:"Krystian Dereziński", description:"A neurobiologist dealing with the processes and disorders of the nervous system; influence of cognitive processes, emotions, stress on the bioelectric activity of the brain." },
    {id:1, src:"furman", name:"Łukasz Furman", description:"In symbiosis with nature in the fields of visual programming, mind research, and coding. Focused professional with 10+ years of experience and proven knowledge of advanced technology, real-time data." },
    {id:3, src:"klaudia", name:"Klaudia Zientek", description:"Engineer & Cognitive Scientist, Researcher in Computational Neuroscience, interested in neurogaming, neurotechnology, neuromarketing and modern types of therapy." },
    {id:4, src:"dr_tolpa", name:"Krzysztof Tołpa", description:" My scientific interests consist of neuroimaging methods, in particular EEG, methods of signal analysis, including Brain -Computer Interface technology and mechanisms of information processing by the brain." },
    {id:5, src:"wers", name:"Weronika Sójka", description:"Cognitive Science Student, Computational Neuroimaging Team Member, Neuroimaging Data Analysis." },
    {id:6, src:"zosia", name:"Zosia Piętka-Danilewicz", description:"Cognitive Science Student Computational Neuroimaging Team Neural Signal and Information Flow Analysis." },
    {id:7, src:"kelayno", name:"Paweł Drojecki", description:"Cognitive science student. Interested in topics such as anxiety and mood disorders, eye-tracking, virtual reality, anthropology and neurotransmitters homeostasis." },
    {id:8, src:"misterius", name:"Natalia Drojecki", description:"Neurobiologist focusing on perception of perspective and processing of speech; neurophysiology; automation." },
    {id:9, src:"snikers", name:"Sławek", description:"I want to be the most powerful scientist like Dr. Stone. " },
  ]

  
export const aboutList = [
    {id:0, src:"BALLS", text:"NeuroTechTOR is a club bringing together people interested in active participation in the development of neurotechnology in Poland. We are students, PhD students, researchers, lecturers, professionals and amateurs in fields such as cognitive science, psychology, computer science, biotechnology, physics, biology, mathematics, philosophy, arts..."},
    {id:1, src:"WAVE", text:"We use technologies such as BCI, EEG, fMRI, MEG, tDCS, TMS, ET and a number of advanced signal analysis methods such as machine learning,  artificial intelligence and others for computational neuroscience."},
    {id:2, src:"LIGHTBULB", text:"Our goal is to study the phenomenon and create solutions that allow to combine neurosciences, engineering, psychology, medicine, computer science and medicine in order to improve the quality of human life. We are interested in diagnosis, therapy and development of users of new solutions."},
    {id:3, src:"EARTH", text:"We are an open group of people from all over Poland, and not only Poland, and our beginning takes place in Toruń - the city of Nicolaus Copernicus, which, as they say, stopped the Sun and moved the Earth. We plan to move people's minds."},
  ]

export const projectList = [
    { 
      id:0, 
      slug:"cognitive-enhancement",
      title:"Cognitive enhancement influences the perception of art", 
      authors:["Weronika Sójka"],
      contributors: ["Krystian Dereziński, ", "Paweł Drojecki, ", "Klaudia Zientek"],
      short_description:"Pilot study aiming to understand how visitors experience and memorize museum environments in condition to emotional stimulation prior to visiting the museum...",
      description:"Pilot study aiming to understand how visitors experience and memorize museum environments in condition to emotional stimulation prior to visiting the museum. In my study, I would like to study how relaxation training affects aesthetic judgements. For future investigation we can try to find out if we can increase possibilities of cognitive functionality thanks to specific emotional stimulation.",
      studydesign:"My research will consist of two stages. Firstable, I plan to analyze EEG signals of people exposed to the relaxation method I chose based on literature overview (Rodriguez et al., 2020). Since I have to make sure that a given type of relaxation produces the desired effect I want to achieve. Subsequently, I would have obtained a 360-degree video to be able to simulate a visit to the museum as realistically as possible thanks to the collaboration with the Museum of the Origins of the Polish State in Gniezno,. Using Virtual Reality and Eye-Tracking recordings, I would analyze the degree of immersion of the subject with art depending on the groups. Furthermore, subjects would be asked for a validation questionnaire consisting of questions regarding the assessment of the reception of specific elements of the exhibition and how well they were remembered just after the study and one week after remotely.",
      background:"Assuming humans are active perceivers, we can consider our emotional states may affect how we unconsciously perceive and memorize the same situation (Zadra & Clore, 2011), we can assume that humans are active perceivers. If so, museums are places where we would like to enhance our cognition however there are still only a few studies searching universal patterns that would influence every recipient of the exhibition. According to the model of aesthetic experience (Leder et al., 2004), cognitive processing of cultural content produces affective and often positive impressions. Latest research showed that stronger affect (i.e. anger) correlates with increased susceptibility to suggestions about false details connected to the presented material (Greenstein & Franklin, 2020). Therefore we can assume that stronger emotions have a visible impact on the audience whereas regulation of affect may influence successive cognition.",
      research_questions:["Does the emotional state affect reception of presented exhibitions?","Does relaxation training have a positive effect on the quality of remembered information?","Does relaxation training affect the aesthetic judgment of cultural content?", "Are we able to conclude about cognitive involvement during contact with the exhibition, at the stage of eye-tracking data analysis?"]
    },
    { 
      id:1, 
      slug:"examination-of-approach-avoidance-conflict",
      title:"Increasing the Self-Regulation of Affect and Action by discovering brain asymmetry patterns while everyday decision making - EEG study", 
      authors:["Zofia Piętka-Danilewicz"],
      contributors: ["Krystian Dereziński, ", "Krzysztof Tołpa"],
      short_description:"Detecting neural correlates (brain asymmetry patterns) of Decision Making in the context of Approach-Avoidance Conflict according to individual differences (personalities and temperament traits) in motivational response.",
      description:"Detecting neural correlates (brain asymmetry patterns) of Decision Making in the context of Approach-Avoidance Conflict according to individual differences (personalities and temperament traits) in motivational response.",
      studydesign:"Responders (N=30) will answer on an approach-avoidance task - 75 conflict-designed alternatives (pictures displayed on the computer screen), by pulling/pushing the joystick while their brain activity will be registered by the EEG system and their pupils' size will be measured by Eye-Tracker. Brain signal data will be acquitted via 64-channels BrainProducts EEG system. LORETA analysis in the BESA program will be performed to visualize the source activation on the cortical level, during Approach-Avoidance Motivation experiment. The pupil arousal will be measured using the TOBI Eye-Tracker. Psychological tests carried out by a psychologist from the psychological testing laboratory: Revised NEO Personality Inventory (NEO PI-R); Strelau Temperament Inventory (FCZ-KT).",
      background:"Investigation the asymmetry in brain activity during decision making, according to Approach-Avoidance Conflict. (Kelley, Hortensius, Schutter, Harmon-Jones, 2017). It is reported that left hemisphere areas are more engaged in the processing of approach stimuli - happy and relaxed emotions, and the right one is dominant encountering avoidance behaviours - angry and sad emotions (Pane, Wibawa, Purnomo, 2019). Investigation approach-avoidance behaviours using ambiguous stimuli i.e. both either positive or both negative, that differ in arousal (Fricke, Vogel, 2020). Human - avoidance motivation and behavioral choices depends on the context and individual differences in motivational responses (personality/temperament traits and others) (Vecchio, Pascalis, 2020). Both factors can affect our decision and reaction speed to the presented stimuli (Ferris et al., 2011). Examination the level of correlation between decisions assessed by participants with measures representing objective X: brain activity reflecting judgements made on neural level, as well as pupil size, measured by eye tracker, which depends on basic behavioural reactions of approach and avoidance (Brambilla, Biella, Kret, 2019).",
      research_questions:["What is the level of brain asymmetry in neuronal response to approach-avoidance decision?","Is affective information processing automatically triggers flexion and extension, independent from the intention to evaluate the stimuli?","How individual differences explain variance in motivational response?","What is the level of the correlation between personality/temperament traits and the approach-avoidance brain response?"]
    },
    {
      id:2, 
      slug:"does-listening",
      title:"Does listening to music boost cognitive ability? Validation of the influence of music provided by Brain.fm on cognitive performance", 
      authors:["Patrycja Misch"],
      contributors: ["Krystian Dereziński"],
      short_description:"Research on the difference in the influence of music on sensors-sensitive people based on the Eysenck test shows that individual differences matter in the context of stimulating the brain with music (Kussner, 2017).",
      description:"Research on the difference in the influence of music on sensors-sensitive people based on the Eysenck test shows that individual differences matter in the context of stimulating the brain with music (Kussner, 2017).",
      studydesign:"Participants will be divided into three groups: a control group (no stimulus), an experimental group (matched music from the 'Brain.fm' application) and a sham group (random music from the 'Brain.fm' application). At the beginning, respondents receive Strelau Temperament Inventory (FCZ-KT) to see if properly selected music will have a greater impact on cognitive functions in sensory-sensitive people. Then depending on the group they receive stimuli or not. During the research, the 8-channel electroencephalograph (EEG) will record neuronal oscillations. For signal analysis, I will use the FFT method, which allows for accurate and quick assessment of the vibration of the signal components. Whereas, when testing the ease of remembering, the respondents will watch a short film and then answer a few questions related to its content.      ",
      background:"Music has been revealed to stimulate the brain by influencing neuronal oscillations (Jancke, Leipold, Burkhard, 2018). The pattern of neuronal activity can be seen as fingerprints of cognitive processes (Siegel, Donner & Engel, 2012). One way to assess the state of concentration or relaxation is to analyze the EEG signal, specifically the amplitude of the alpha and beta bands (George, Lotte, Abad, Lécuyer, 2011). In recent years, the use of functional music has become increasingly popular - that is, music that in a specific, intentional way influences the user's cognitive abilities (Jones, Schumacher, 1992). Functional music is designed to have effects on neurophysiology by means of acoustic modulation (salience reduction, 3D spatialization, modulation to alter brain activity, etc.). This innovative form of music is generated and tested by the Brain.fm team, which opens the door to further research in this aspect (www.brain.fm, 2021).",
      research_questions:["How sound features affect behavior?","How functional music contributes to the level of relaxation and concentration in participants?","Does functional music have a greater impact on the level of concentration and relaxation in people with higher sensory sensitivity?"]
    },
    {
      id:3, 
      slug:"influence-of-the-archery-training",
      title:"Influence of the archery training on mindfulness and changes in the perception of anxiety. Study with the use of EEG and eye-tracking glasses", 
      authors:["Natalia Pawłowska"],
      contributors: ["Sławomir Duda"],
      short_description:"Detecting correlates between archery and EEG activity during a six weeks training. Verification of archery as a novel mindfulness method and checking if it can help with a general anxiety disorder or with feeling anxious.",
      
      description:"Detecting correlates between archery and EEG activity during a six weeks training. Verification of archery as a novel mindfulness method and checking if it can help with a general anxiety disorder or with feeling anxious.",
      
      studydesign:"Participants (N = 30) during a six weeks period will train archery (2 times a week for 30 minutes). During training their neuronal activity will be measured by using 8-channels EEG system [Perun-8 (BrainTech)]. Eye movement also will be recorded to track fixation points and gaze duration – glasses with eye-tracker will be used to do this. Before starting the training participants will fill out the STAI test (). The test will be retaken after a period of six weeks, i.e. upon completing the archery training. The size of a target will vary depending on the participant's level of focus. The more focused the participant is, the larger the target he/she will shoot at becomes. To control this variable I will use a program, which will link the appearance of the appropriate low beta frequency (13–16 Hz) (Tarrant et al., 2018; Huang & Lo, 2009) with the size of the target.",

      background:"This study introduces promising anxiety, and possibly depression or ADHD, therapy methods (Tarrant, 2017). Such training can be more beneficial than most neurofeedback sessions since it is combined with physical exercises. It will also enable a better mindfulness practice than normal archery, as it will force the subject to control his/hers focus and not yield to excitement when the target grows larger. Moreover, the program created for this study may be useful also during different experiments as it allows researchers to connect the participant’s neural activity with stimuli they receive.",

      research_questions:["How does archery training affect mindfulness?","Can archery be a mindfulness method which reduces anxiety?","How does eye movement change during a six week period of archery training?"]
    },
    {
      id:4, 
      slug:"control-drone-using-eeg",
      title:"In search of new ways to control drone using EEG and machine learning", 
      authors:["Monika Lewandowska"],
      contributors: ["Krystian Dereziński, ", "Krzysztof Tołpa"],
      short_description:"This study aims to show that we can find new possibilities to create BCI methods for reading and analyzing EEG data to create predictions, triggers, and markers for setting the position of the drone in R3 space.",
      
      description:"This study aims to show that we can find new possibilities to create BCI methods for reading and analyzing EEG data to create predictions, triggers, and markers for setting the position of the drone in R3 space.",
      
      studydesign:"Using visual-based environments (TouchDesigner) we can make rapid prototyping using methods like Deep Learning, Siamese Network, and Triplet Loss methods. Computing these networks on GPU (compute shader and GLSL) creates a way to train models faster than other libraries on single GPU units like Geforce GTX1080 or RTX2080. Further areas of research involve generating predictions over a big set of data (big data) and finding patterns for creating triggers to control IOT (Internet Of Things) with EEG brainwaves. This method involves using raw data with a notch filter as input for the prediction model, data can be stored as 2D textures(QEEG) in 3D arrays for future analyses. Training neural networks using textures as input data gives us the way to perceive different aspects of signal over brain activity. From generating different methods of interpolation to unification for EEG big data datasets for a non-changing architecture of neural network model.",

      background:"The technology of brain-computer interface (BCI) provides a new way of interacting with devices, by allowing people to control a computer system through their brain signals without the need for physical activity. BCI has huge potential as an assistive technology, for enabling  and rehabilitative purposes. Unmanned aerial devices (UAV) or drones have been gaining popularity in our daily lives, such as in photography. Research has also been done in designing BCI for drone piloting. Such BCIs provide users with a hands-free method to control the drone. This field has a potential in allowing the disabled to reach and interact with objects via the drone [4]. It can be also considered as a tool in neurofeedback therapies. Electroencephalography (EEG) is one of the principle methods of acquiring brain signals non-invasively in BCI control applications. Most research in BCI drone control uses research-grade EEG headsets with 14 to 64 wet electrodes. While such devices provide the benefit of high accuracy, they have limited usability due to tedious set-up and cleanup procedures, high costs and restricted movement. On the other hand, consumer-grade EEG devices are cheaper and have better usability, but are more vulnerable to noise and have limited sensors at fixed locations. Nonetheless, consumer-grade EEG systems have been shown to be able to demonstrate various neural phenomena.",

      research_questions:["Will usage of 2D textures in 3D arrays give the opportunity to prototype ways of controlling IOT?","Can archery be a mindfulness method which reduces anxiety?","How does eye movement change during a six week period of archery training?"]
    },

  ]